### ISSUE TITLE
F5 Generation causes Uncaught SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jevo** [TUD-INF-IAI-MCI/agsbs_atom_package#285]
[Enter steps to reproduce:]

1. Launch the package
2. Open md-file 
3. Press F5

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Python3**: Python 3.6.3
**Thrown From**: [agsbs-atom-package](https://github.com/TUD-INF-IAI-MCI/agsbs_atom_package) package 0.17.3

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

### Atom console output

```
exec error: Error: Command failed: matuc_js mk "/Users/voegler/Documents/atom_test/k01" 
Traceback (most recent call last):
  File "/usr/local/bin/matuc_js", line 50, in <module>
    main_inst.run(sys.argv)
  File "/Users/admin/github/AGSBS-infrastructure/matuc_impl/__init__.py", line 192, in run
    ret = func(invokation_command, args[2:])
  File "/Users/admin/github/AGSBS-infrastructure/matuc_impl/__init__.py", line 485, in handle_mk
    self.output_formatter.emit_result(format_errors())
  File "/Users/admin/github/AGSBS-infrastructure/matuc_impl/__init__.py", line 449, in format_errors
    mistakes = mistkerl.run(options.input)
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 119, in run
    self.__run_filters_on_file(file_path, paragraphs)
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 179, in __run_filters_on_file
    for issue in self.get_issues(MistakeType.formulas, file_path):
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 80, in get_issues
    return list(i for i in (i() for i in issues) # instanciate
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 80, in <genexpr>
    return list(i for i in (i() for i in issues) # instanciate
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/mistkerl.py", line 80, in <genexpr>
    return list(i for i in (i() for i in issues) # instanciate
  File "/Users/admin/github/AGSBS-infrastructure/MAGSBS/quality_assurance/latex.py", line 35, in __init__
    self.pattern = re.compile(r".*(\left|\big|\Big)\(.*?begin{(array|matrix)")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 502, in _parse
    code = _escape(source, this, state)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_parse.py", line 401, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
sre_constants.error: bad escape \l at position 3
```

**Comment by jevo** [comment]
That error is caused by Python version 3.6.

A quick solution is a downgrade to version **3.5**.

**Comment by jevo** [comment]
This was a matuc error see https://github.com/TUD-INF-IAI-MCI/AGSBS-infrastructure/issues/49 and is fixed with https://github.com/TUD-INF-IAI-MCI/AGSBS-infrastructure/commit/00179cacac868bd7dfd01e6911dc16ed80e0e3d6
